### ISSUE TITLE
Is this package required?

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [jctaoo/elecrun#54]
Hi, I was going to update 'cspell' but I saw that it is not used anywhere in the code, after all it is a cli program. It only appears at 'package.json' and yarn.lock.
It is a code spell checker, so I was wondering if you use it (in that case I'll just update to latest), or if it can be thrown out?
If you use it, can you/I put in 'package.json' the script for it's usage, just to show that it is useful?

**Comment by jctaoo** [comment]
I have removed it in branch [next](https://github.com/jctaoo/elecrun/tree/next).
